@extends('layouts.app')

@section('title', app()->getLocale() === 'ar' ? $event->name_ar : $event->name_en)

@section('content')
    @include('landing.partials.nav', ['event' => $event])
    @include('landing.partials.hero', ['event' => $event])
    @include('landing.partials.about', ['event' => $event])
    @include('landing.partials.stats', ['event' => $event])
    @include('landing.partials.speakers', ['event' => $event])
    @include('landing.partials.workshops-teaser', ['event' => $event])
    @include('landing.partials.agenda-teaser', ['event' => $event])
    @include('landing.partials.tickets', ['event' => $event])
    @include('landing.partials.awards-teaser', ['event' => $event])
    @include('landing.partials.gallery', ['event' => $event])
    @include('landing.partials.testimonials', ['event' => $event])
    @include('landing.partials.partners', ['event' => $event])
    @include('landing.partials.faq', ['event' => $event])
    @include('landing.partials.location', ['event' => $event])
    @include('landing.partials.contact', ['event' => $event])
    @include('landing.partials.footer', ['event' => $event])
@endsection
